version: '3.9'

services:
  djangoapp:
    build: .
    volumes:
      # Espelha o código para atualizações em Python
      - ./djangoapp:/djangoapp
      # Usa um volume nomeado para o collectstatic (evita conflito de permissão)
      - django_static_volume:/djangoapp/staticfiles
      # Espelha a pasta de mídia para o Django salvar os uploads
      - ./mediafiles:/djangoapp/mediafiles
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      # Nginx serve o CSS/JS diretamente da sua pasta local (para live-reload)
      - ./staticfiles:/var/www/staticfiles
      # Nginx tem acesso aos estáticos do admin via volume nomeado
      - django_static_volume:/var/www/django_admin_static
      # Nginx serve as imagens diretamente da sua pasta local
      - ./mediafiles:/var/www/mediafiles
    depends_on:
      - djangoapp

volumes:
  django_static_volume: